---
# Spring Cloud配置
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
eureka:
  instance:
    prefer-ip-address: true
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://150.150.187.30:11006/eureka/